<a href="https://colab.research.google.com/github/RichardZambrano05/InteligenciaArtificial/blob/main/Parctica2_IA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.random.randint(1,10,(3,4))
print(a)
tmp=np.mean(a)
print(tmp)
print(a.mean())
tmp=a.mean(axis=1)
print(tmp)
tmp=a.mean(axis=0)
print(tmp)
tmp=a.sum()
print(tmp)
mediana=np.median(a,axis=1)
print(mediana)

[[2 4 2 9]
 [2 9 2 3]
 [7 3 8 3]]
4.5
4.5
[4.25 4.   5.25]
[3.66666667 5.33333333 4.         5.        ]
54
[3.  2.5 5. ]


In [ ]:
#sorting
b=np.random.randn(10)
print(b)
print(b.shape)
b.sort()
print(b)

[-0.51096499  0.54951162  0.1848824   1.19938015  0.65290552  0.23855874
  0.38980995 -1.71505012  0.33838686 -0.34737621]
(10,)
[-1.71505012 -0.51096499 -0.34737621  0.1848824   0.23855874  0.33838686
  0.38980995  0.54951162  0.65290552  1.19938015]


In [ ]:
c=np.array([2,3,4,2,5,3,5])
print(np.unique(c))

[2 3 4 5]


In [ ]:
string1=np.array(['desk', 'chair', 'bulb'])
string2=np.array(['lamp', 'bulb', 'chair'])

tmp1=np.intersect1d(string1,string2)
print(tmp1)
tmp2=np.union1d(string1,string2)
print(tmp2)
tmp3=np.setdiff1d(string1,string2)
print(tmp3)

tmp4=np.in1d(string1,string2)
print(tmp4)


['bulb' 'chair']
['bulb' 'chair' 'desk' 'lamp']
['desk']
[False  True  True]


In [ ]:
#BROADCASTING
aux=np.zeros((4,3))
print(aux)
replica=np.array([1,2,1])
aux=aux+replica
print(aux)
replicacol=np.array([10,10,10])
print(replicacol.shape)
replicacol=np.reshape(replicacol,(3,1))
print(replicacol.shape)
aux=np.zeros((3,3))
aux1=aux+replicacol
print(aux1)

vector=np.array([45])
matrixZeros=np.zeros((5,5))
print(matrixZeros)
print(matrixZeros+vector)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]]
(3,)
(3, 1)
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]]
