<a href="https://colab.research.google.com/github/RichardZambrano05/InteligenciaArtificial/blob/main/Practica3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.random.randint(1,10,(3,4))
print(a)
b=np.random.randint(1,10,(3,4))
print(b)

[[9 8 4 9]
 [7 8 6 7]
 [6 5 9 7]]
[[5 4 5 7]
 [4 8 9 9]
 [4 2 1 3]]


In [ ]:
a=np.random.randn(10)
print(a)
b=np.random.randn(10)
print(b)

[ 0.74121045  0.19293398  1.61533102  0.70110309 -0.79059481  1.13363359
 -0.81096494  2.15954945 -1.02034203  0.56328026]
[ 0.57752511  0.7612428   0.656573    2.3181241   0.79968337 -0.92671442
 -1.3433176   1.59513982 -0.11345404 -1.50884255]


In [ ]:
import numpy as np
tmp=np.arange(15)
print(tmp)
tmp1=tmp[5:10]
print(tmp1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[5 6 7 8 9]


In [ ]:
import numpy as np
a=np.array([5,7,9,8,6,4,5])
b=np.array([6,3,4,8,9,7,1])
def max_array(a,b):
  r=np.maximum(a,b)
  return r
resul=max_array(a,b)
print(resul)



[6 7 9 8 9 7 5]


In [ ]:
arr=np.arange(9).reshape(3,3)
print("Original Matriz:")
print(arr)
arr[:,[1,2]]=arr[:,[2,1]]
print("\nIntercambiadas Matriz:")
print(arr)

Original Matriz:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Intercambiadas Matriz:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [ ]:
import numpy as np
random_array=5+10*np.random.random((5,3))
print(random_array)

[[ 5.854831    8.75722772  7.15869742]
 [11.45961307 13.75925234 11.6402783 ]
 [ 6.46686471 13.32680845 14.2295923 ]
 [14.65024615  7.77381147 10.55028955]
 [11.96891357  7.89646677  8.37906238]]
