<a href="https://colab.research.google.com/github/Nodnarbx69/inteligenciaArtificial/blob/main/01Julio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a=np.array([11,22,33])
print(a.shape)
print(type(a))
print(a)

print(a[0], a[1])
print(a[0:2])
print(a[1:])

a[1]=888
print(a)

(3,)
<class 'numpy.ndarray'>
[11 22 33]
11 22
[11 22]
[22 33]
[ 11 888  33]


In [2]:
b=np.array([[11,22,33],[44,55,66],[77,88,99]])
print(b.shape)
print(type(b))
print(b)

print(b[1,1])
aux=b[1:,1:].copy()
print(aux.shape)
print(aux)

print('ANTES....')
print(b)
print(aux)

aux[1,1]=1000

print('DESPUES...')
print(b)
print(aux)


(3, 3)
<class 'numpy.ndarray'>
[[11 22 33]
 [44 55 66]
 [77 88 99]]
55
(2, 2)
[[55 66]
 [88 99]]
ANTES....
[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[55 66]
 [88 99]]
DESPUES...
[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[  55   66]
 [  88 1000]]


In [3]:
c=np.zeros((4,4))
print(c)
print(c.shape)

d=np.full((4,4),9)
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [5]:
g=np.random.random((5,5))
print(g)

[[0.77564341 0.1880224  0.17979463 0.38522346 0.93963234]
 [0.86543739 0.68772132 0.37372643 0.71922882 0.98811457]
 [0.72571328 0.83032655 0.52625185 0.27277825 0.66160893]
 [0.66005137 0.90232006 0.02845117 0.35431231 0.27225264]
 [0.4588046  0.00514902 0.73749333 0.25512075 0.71331903]]


In [6]:
tmp1=np.random.randint(1,21, size=(4,4))
print(tmp1)
rows=np.array([0,1,2,0])
cols=np.arange(4)

print(rows)
print(cols)

[[ 5  2 11 12]
 [ 8 19 12 17]
 [13  7 17  9]
 [19  4  5 14]]
[0 1 2 0]
[0 1 2 3]


In [7]:
tmp1[rows, cols]=100
print(tmp1)

[[100   2  11 100]
 [  8 100  12  17]
 [ 13   7 100   9]
 [ 19   4   5  14]]


In [8]:
tmp2=np.random.randint(20,50, size=(6,6))
print(tmp2)

[[27 22 33 27 35 45]
 [23 20 22 35 32 24]
 [40 26 22 40 37 43]
 [47 35 21 22 26 35]
 [48 38 20 32 24 34]
 [42 46 31 37 48 44]]


In [9]:
mask = tmp2 > 45
print(mask)
elemay = tmp2[mask]

print("Elementos mayores a 45:")
print(elemay)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [ True False False False False False]
 [ True False False False False False]
 [False  True False False  True False]]
Elementos mayores a 45:
[47 48 46 48]


In [10]:
tmp3=np.random.randint(1,100, size=(10,10))
print(tmp3)

[[49 22 97 18  6 52 96 31 19 41]
 [62  8 34 48 60 54 50 43  1 19]
 [67  4 35 20 89 67 67 19 22 62]
 [57 94 58 83 82 30 16 23 30 15]
 [78 94 28 93 83 66 71 78 71  6]
 [90 34 95 84 87 95 71  5 17 38]
 [ 2 52 15  3 45 19 26 83 73 27]
 [12 46 28 72 15  6 93 47 32 48]
 [55 65 95 25  1 18 88 52 66 88]
 [82 53 25 61 30 50 24 77 78 38]]


In [11]:
mask2 = ((tmp3%2)==0)
# print(mask2)
elepar = tmp3[mask2]

print("Elementos pares:")
print(elepar)

Elementos pares:
[22 18  6 52 96 62  8 34 48 60 54 50  4 20 22 62 94 58 82 30 16 30 78 94
 28 66 78  6 90 34 84 38  2 52 26 12 46 28 72  6 32 48 18 88 52 66 88 82
 30 50 24 78 38]


In [12]:
tmp4=np.array([1,2,3,4,5],dtype=np.float64)
print(tmp4.dtype)
print(tmp4)


float64
[1. 2. 3. 4. 5.]


In [14]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x)
print(y)
print('SUMA')
print(np.add(x,y))
print('RESTA')
print(np.subtract(x,y))
print('MULTIPLICACION')
print(np.multiply(x,y))
print('DIVISION')
print(np.divide(x,y))
print('RAIZ')
print(np.sqrt(x))
print('POTENCIA')
print(np.power(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
SUMA
[[ 6  8]
 [10 12]]
RESTA
[[-4 -4]
 [-4 -4]]
MULTIPLICACION
[[ 5 12]
 [21 32]]
DIVISION
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
RAIZ
[[1.         1.41421356]
 [1.73205081 2.        ]]
POTENCIA
[[    1    64]
 [ 2187 65536]]


In [15]:
tmp5=np.random.randint(1,10, size=(2,5))
print(tmp5)
aux=tmp5.mean()
print(aux)

[[9 8 6 5 7]
 [4 1 2 3 3]]
4.8


In [16]:
print(tmp5.mean(axis=1))
print(tmp5.mean(axis=0))

[7.  2.6]
[6.5 4.5 4.  4.  5. ]
