<a href="https://colab.research.google.com/github/RichardZambrano05/InteligenciaArtificial/blob/main/Trabajo_aut%C3%B3nomo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Autor: Richard Eduardo Zambrano Cedeño
# Materia: Inteligencia Artificial
# Curso: 8vo semestre de TI

In [ ]:
# Import numpy as np and see the version

# your code here
#pass

import numpy as np

# Verificar la versión de numpy
print(np.__version__)


1.25.2


In [ ]:
# Create a 1D array of numbers from 0 to 9
# your code here
#pass

import numpy as np

# Crear un array unidimensional de números del 0 al 9
array_1d = np.arange(10)
print(array_1d)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Create random vector of size 10 and replace the maximum value by 0
#pass

import numpy as np

# Crear un vector aleatorio de tamaño 10
random_vector = np.random.rand(10)
print("Vector aleatorio original:", random_vector)

# Reemplazar el valor máximo en el vector por 0
random_vector[random_vector.argmax()] = 0
print("Vector después de reemplazar el valor máximo por 0:", random_vector)

Vector aleatorio original: [0.50471073 0.58434849 0.72105252 0.11904992 0.03093553 0.38479483
 0.18585795 0.81212308 0.4300918  0.46746996]
Vector después de reemplazar el valor máximo por 0: [0.50471073 0.58434849 0.72105252 0.11904992 0.03093553 0.38479483
 0.18585795 0.         0.4300918  0.46746996]


In [ ]:
# Print the number 8 from the array below:
# arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
#pass

import numpy as np

# Array dado
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Imprimir el número 8
number_8 = arr[1, 2]
print(number_8)


8


In [ ]:
# Print the numbers [3, 4, 5] from the array below:
# arr = np.array([1,2,3,4,5,6,7])
#pass

import numpy as np

# Dado de matriz
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Imprimir los números [3, 4, 5]
subset = arr[2:5]
print(subset)


[3 4 5]


In [ ]:
# Print the last 4 numbers from the array below:
# arr = np.array([1,2,3,4,5,6,7])
#pass

import numpy as np

# Dado de matriz
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Imprimir los últimos 4 números
last_four_numbers = arr[-4:]
print(last_four_numbers)

[4 5 6 7]


In [ ]:
# Create a 3×3 numpy array of all True’s
# your code here
#pass

import numpy as np

# Crear un array de 3x3 con todos los valores True
array_true = np.full((3, 3), True)
print(array_true)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# Extract all odd numbers from arr
# your code here
#pass

import numpy as np

# Dado de matriz
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Extraer todos los números impares
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]


In [ ]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
#pass

import numpy as np

# Crear un vector con valores del 10 al 49
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Reverse a vector (first element becomes last)
#pass

def reverse_vector(vector):
    return vector[::-1]

# Ejemplo:
original_vector = [1, 2, 3, 4, 5]
reversed_vector = reverse_vector(original_vector)
print("Original:", original_vector)
print("Invertido:", reversed_vector)

Original: [1, 2, 3, 4, 5]
Invertido: [5, 4, 3, 2, 1]


In [ ]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
#pass

import numpy as np

# Uuna matriz de 10x10 con valores enteros aleatorios entre 0 y 100
array = np.random.randint(0, 101, size=(10, 10))

# Encuentra valores mínimos y máximos.
min_value = np.min(array)
max_value = np.max(array)

print("Array:")
print(array)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)

Array:
[[ 28  99   3  39  38  43  30  98  10  98]
 [ 49  62  55  99  93  62  30 100  46  12]
 [ 23  32   4  78  93  91  75  54  72   4]
 [ 62  81  67   7  73  73  28  50   6  86]
 [100  50  63  34  26  50  30  13  95  78]
 [  4  60  85  50  37  68  57  13  56  81]
 [ 28  44  82  28   3  87  37  64  84   6]
 [ 23  70   4  71  60  22  21  61  50  80]
 [ 93  58  80  36  74  16  22  51  50  60]
 [ 95  72  49  21  13  80  17  41  40  70]]

Minimum value: 3
Maximum value: 100


In [ ]:
# Create a 3x3x3 array with random values
#pass

import numpy as np

# Una matriz de 3x3x3 con valores aleatorios
array = np.random.rand(3, 3, 3)

print("Matriz 3x3x3 con valores aleatorios:")
print(array)

Matriz 3x3x3 con valores aleatorios:
[[[0.71095236 0.07312702 0.5400237 ]
  [0.95783179 0.73353108 0.34901682]
  [0.59205141 0.84854692 0.77100099]]

 [[0.88315324 0.21129338 0.74678934]
  [0.67281142 0.15657174 0.52087224]
  [0.85461911 0.81253319 0.05939898]]

 [[0.18535721 0.56198701 0.42645627]
  [0.30741441 0.42819907 0.06090104]
  [0.88068825 0.70611889 0.99901252]]]


In [ ]:
# Replace all odd numbers in arr with -1
# your code here
#pass

import numpy as np

# Matriz de ejemplo
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Reemplazar números impares con -1
arr[arr % 2 != 0] = -1

print("Matriz modificada:")
print(arr)

Matriz modificada:
[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


In [ ]:
# Create an array of type float
#pass

import numpy as np

# Crea una matriz de tipo float
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]], dtype=float)

print("Matriz de tipo flotante:")
print(arr)

Matriz de tipo flotante:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
# Convert a 1D array to a 2D array with 2 rows
# your code here
#pass

import numpy as np

# Ejemplo de matriz 1D
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Convertir a una matriz 2D con 2 filas
arr_2d = arr_1d.reshape(2, -1)  # -1 en remodelación infiere la dimensión restante

print("Original 1D matriz:")
print(arr_1d)
print("\nMatriz 2D convertida con 2 filas:")
print(arr_2d)

Original 1D matriz:
[1 2 3 4 5 6]

Matriz 2D convertida con 2 filas:
[[1 2 3]
 [4 5 6]]


In [ ]:
# How to find common values between two arrays?

# Z1 = np.random.randint(0,10,10)
# Z2 = np.random.randint(0,10,10)
#pass

import numpy as np

# Matrices de ejemplo
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

# Encuentre valores comunes entre Z1 y Z2
common_values = np.intersect1d(Z1, Z2)

print("Matriz Z1:", Z1)
print("Matriz Z2:", Z2)
print("\nValores comunes entre Z1 y Z2:", common_values)

Matriz Z1: [5 3 2 9 5 9 4 5 3 1]
Matriz Z2: [8 5 6 0 7 5 1 8 8 8]

Valores comunes entre Z1 y Z2: [1 5]


In [ ]:
#  Consider two random array A and B, check if they are equal


# A = np.random.randint(0,2,5)
# B = np.random.randint(0,2,5)

#pass

import numpy as np

# Generar matrices aleatorias A y B
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# Compruebe si las matrices A y B son iguales
are_equal = np.array_equal(A, B)

print("Matriz A:", A)
print("Matriz B:", B)

if are_equal:
    print("\nLas matrices A y B son iguales.")
else:
    print("\nLas matrices A y B no son iguales.")

Matriz A: [1 0 1 0 1]
Matriz B: [0 0 0 0 1]

Las matrices A y B no son iguales.


In [ ]:
# Stack arrays a and b vertically
# your code here
#pass

import numpy as np

# Matrices de ejemplo
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7, 8, 9],
              [10, 11, 12]])

# Apilar matrices a y b verticalmente
stacked_array = np.vstack((a, b))

print("Matriz a:")
print(a)
print("\nMatriz b:")
print(b)
print("\nMatriz apilada verticalmente:")
print(stacked_array)

Matriz a:
[[1 2 3]
 [4 5 6]]

Matriz b:
[[ 7  8  9]
 [10 11 12]]

Matriz apilada verticalmente:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Stack the arrays a and b horizontally.
# your code here
#pass

import numpy as np

# Matrices de ejemplo
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# Apilar las matrices a y b horizontalmente
stacked_array = np.hstack((a, b))

print("Matriz a:")
print(a)
print("\nMatriz b:")
print(b)
print("\nMatriz apilada horizontalmente:")
print(stacked_array)


Matriz a:
[[1 2]
 [3 4]]

Matriz b:
[[5 6]
 [7 8]]

Matriz apilada horizontalmente:
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Get all items between 5 and 10 from array tmp.
# your code here
#import numpy as np
#tmp = np.arange(15)
# pass

import numpy as np

tmp = np.arange(15)

# Consigue artículos entre 5 y 10
result = tmp[(tmp > 5) & (tmp < 10)]

print("Matriz original tmp:")
print(tmp)
print("\nArtículos entre 5 y 10:")
print(result)

Matriz original tmp:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Artículos entre 5 y 10:
[6 7 8 9]


In [ ]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


# your code here
#import numpy as np

#def maxx(x, y):
 #   """Get the maximum of two items"""
  #  if x >= y:
   #     return x
    #else:
     #   return y

#maxx(1, 5)

import numpy as np

def pair_max(x, y):
    """Obtenga el máximo de elementos de dos matrices"""
    return np.maximum(x, y)

# Ejemplo:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

result = pair_max(a, b)
print(result)

[6 7 9 8 9 7 5]


In [ ]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]


#arr = np.arange(9).reshape(3,3)
#print(arr)
# your code here
#pass

import numpy as np

arr = np.arange(9).reshape(3, 3)
print("Original matriz:")
print(arr)

# Intercambiar columnas 1 y 2
arr[:, [1, 2]] = arr[:, [2, 1]]

print("\nMatriz después de intercambiar las columnas 1 y 2:")
print(arr)


Original matriz:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Matriz después de intercambiar las columnas 1 y 2:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [ ]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

import numpy as np

# Genere una matriz de 5x3 de números decimales aleatorios entre 5 y 10
arr = np.random.uniform(5, 10, size=(5, 3))

print("Matriz aleatoria de 5x3 entre 5 y 10:")
print(arr)


Matriz aleatoria de 5x3 entre 5 y 10:
[[5.8527658  7.00298239 9.90961547]
 [9.8063239  5.35850944 9.60534975]
 [9.39075859 6.88198431 5.16793111]
 [8.63358045 9.29895661 6.30429001]
 [7.96550619 7.67657021 9.7100466 ]]
